---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt
name: elasticsearch

variables:
- name: ssl_ca
  type: certificate
  options:
    is_ca: true
    common_name: elasticsearch-ssl
- name: transport_ca
  type: certificate
  options:
    is_ca: true
    common_name: elasticsearch-transport

releases:
- name: osb-bosh-elasticsearch
  version: latest
- name: prometheus
  version: latest

update:
  canaries: 1
  canary_watch_time: 1500-30000
  update_watch_time: 1500-30000
  max_in_flight: 2

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 621.50

instance_groups:
- name: general_nodes
  instances: 0
  vm_type: default
  persistent_disk_type: medium
  stemcell: default
  networks:
  - name: service
  azs:
  - z1
  jobs:
  - name: elasticsearch
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: discovery_nodes}
    provides:
      database: {as: discovery_nodes, shared: true}
  - name: smoke-tests
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: discovery_nodes}
    release: osb-bosh-elasticsearch
  - name: backup-agent
    release: osb-bosh-elasticsearch
    consumes:
      database:
        from: discovery_nodes
    properties:
      backup_agent:
        skip_storage: true
  - name: elasticsearch_exporter
    release: prometheus
    properties:
      elasticsearch_exporter:
        es:
          uri: https://elastic:((elastic.password))@127.0.0.1:9200
#          ca_cert: http_ssl.ca
          ssl_skip_verify: true
          cluster_settings: true
          indices: true
          indices_settings: true
          shards: true
  - name: blackbox_exporter
    release: prometheus
    properties:
      blackbox_exporter:
        config:
          modules:
            http_2xx:
              prober: http
              http:
                basic_auth:
                  username: elastic
                  password: ((elastic.password))
                tls_config:
                  insecure_skip_verify: true
  properties:
    elasticsearch:
      cluster_name: elasticsearch-cluster
      node:
        allow_master: true
        allow_data: true
        allow_ingest: true
      xpack:
        security:
          http:
            ssl:
              certificate-authorities: ((ssl_ca.certificate))
              ca-key: ((ssl_ca.private_key))
          transport:
            ssl:
              certificate-authorities: ((transport_ca.certificate))
              ca-key: ((transport_ca.private_key))
#      discovery:
#        minimum_master_nodes: 1 # (Number of master-eligible nodes / 2) - 1
- name: master_eligible_nodes
  instances: 0
  vm_type: default
  persistent_disk_type: small
  stemcell: default
  networks:
  - name: service
  azs:
  - z1
  jobs:
  - name: elasticsearch
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: discovery_nodes}
    provides:
      database: {as: master_eligible_nodes}
  - name: smoke-tests
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: master_eligible_nodes}
  - name: backup-agent
    release: osb-bosh-elasticsearch
    consumes:
      database:
        from: discovery_nodes
    properties:
      backup_agent:
        skip_storage: true
  properties:
    elasticsearch:
      cluster_name: elasticsearch-cluster
      node:
        allow_master: true
      xpack:
        security:
          http:
            ssl:
              certificate-authorities: ((ssl_ca.certificate))
              ca-key: ((ssl_ca.private_key))
          transport:
            ssl:
              certificate-authorities: ((transport_ca.certificate))
              ca-key: ((transport_ca.private_key))
#      discovery:
#        minimum_master_nodes: 1 # (Number of master-eligible nodes / 2) - 1
- name: ingest_nodes
  instances: 0
  vm_type: default
  persistent_disk_type: small
  stemcell: default
  networks:
  - name: service
  azs:
  - z1
  jobs:
  - name: elasticsearch
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: discovery_nodes}
    provides:
      database: {as: ingest_nodes, shared: true}
  - name: smoke-tests
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: ingest_nodes}
  - name: backup-agent
    release: osb-bosh-elasticsearch
    consumes:
      database:
        from: discovery_nodes
    properties:
      backup_agent:
        skip_storage: true
  properties:
    elasticsearch:
      cluster_name: elasticsearch-cluster
      node:
        allow_ingest: true
      xpack:
        security:
          http:
            ssl:
              certificate-authorities: ((ssl_ca.certificate))
              ca-key: ((ssl_ca.private_key))
          transport:
            ssl:
              certificate-authorities: ((transport_ca.certificate))
              ca-key: ((transport_ca.private_key))
#      discovery:
#        minimum_master_nodes: 1 # (Number of master-eligible nodes / 2) - 1
- name: coordinating_nodes
  instances: 0
  vm_type: default
  persistent_disk_type: small
  stemcell: default
  networks:
  - name: service
  azs:
  - z1
  jobs:
  - name: elasticsearch
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: discovery_nodes}
    provides:
      database: {as: coordinating_nodes, shared: true}
  - name: smoke-tests
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: coordinating_nodes}
  - name: backup-agent
    release: osb-bosh-elasticsearch
    consumes:
      database:
        from: discovery_nodes
    properties:
      backup_agent:
        skip_storage: true
  properties:
    elasticsearch:
      cluster_name: elasticsearch-cluster
      xpack:
        security:
          http:
            ssl:
              certificate-authorities: ((ssl_ca.certificate))
              ca-key: ((ssl_ca.private_key))
          transport:
            ssl:
              certificate-authorities: ((transport_ca.certificate))
              ca-key: ((transport_ca.private_key))
#      discovery:
#        minimum_master_nodes: 1 # (Number of master-eligible nodes / 2) - 1
- name: data_nodes
  instances: 0
  vm_type: default
  persistent_disk_type: medium
  stemcell: default
  networks:
  - name: service
  azs:
  - z1
  jobs:
  - name: elasticsearch
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: discovery_nodes}
    provides:
      database: {as: data_nodes}
  - name: smoke-tests
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: data_nodes}
  - name: backup-agent
    release: osb-bosh-elasticsearch
    consumes:
      database:
        from: discovery_nodes
    properties:
      backup_agent:
        skip_storage: true
  properties:
    elasticsearch:
      cluster_name: elasticsearch-cluster
      node:
        allow_data: true
      xpack:
        security:
          http:
            ssl:
              certificate-authorities: ((ssl_ca.certificate))
              ca-key: ((ssl_ca.private_key))
          transport:
            ssl:
              certificate-authorities: ((transport_ca.certificate))
              ca-key: ((transport_ca.private_key))
#      discovery:
#        minimum_master_nodes: 1 # (Number of master-eligible nodes / 2) - 1
